[project]
name = "automate-ml-for-kaggle"
version = "0.1.0"
description = "Automate ML workflows"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ag2[jupyter-executor,openai]>=0.11.2",
    "scikit-learn",
    "pandas",
    "matplotlib",
    "seaborn",
    "xgboost",
    "lightgbm",
    "catboost",
    "python-dotenv",
    "typer",
    "pydantic",
    "PyYAML",
    "requests",
]
